spring:
  main:
    web-application-type: none
  banner:
    location: classpath:banner.txt
  ai:
    vertex:
      ai:
        gemini:
          project-id: totemic-stack-367712
          location: us-central1
          transport: REST
          credentials-uri: file:../google-credentials.json
          chat:
            options:
              model: gemini-2.0-flash-exp
              temperature:  0.7

    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: llama3.2
          temperature: 0.7

    mcp:
      client:
        enabled: true
        type: SYNC
        name: "mcp"
        request-timeout: 30s

        toolcallback:
          enabled: true
