spring:
  main:
    web-application-type: none
  banner:
    location: classpath:banner.txt
  ai:
    google-genai:
      project-id: totemic-stack-367712
      location: us-central1
      use-vertex-ai: true
      credentials-uri: file:../google-credentials.json

    ollama:
      base-url: http://localhost:11434
