spring:
  main:
    web-application-type: none
  banner:
    location: classpath:banner.txt
  ai:
    vertex:
      ai:
        gemini:
          project-id: totemic-stack-367712
          location: us-central1
          transport: REST
          credentials-uri: file:../google-credentials.json

    ollama:
      base-url: http://localhost:11434

    mcp:
      client:
        enabled: true
        type: SYNC
        name: "mcp"
        request-timeout: 30s

        toolcallback:
          enabled: true
